In [2]:
import pandas as pd
about_player = pd.read_csv('./data/about_players_2025.csv')
about_player

,Player,#,Class,Pos,Height,Weight,Hometown,High School,RSCI Top 100,Summary
0,John Tonje,9,SR,G,6-5,222,"Omaha, NE",Omaha Central HS,NaN,"19.6 Pts, 5.3 Reb, 1.8 Ast"
1,John Blackwell,25,SO,G,6-4,194,"Highland Park, MI",Brother Rice (MI),NaN,"15.8 Pts, 5.1 Reb, 2.2 Ast"
2,Steven Crowl,22,SR,F,7-0,217,"Eagan, MN",Eastview HS,NaN,"9.9 Pts, 5.3 Reb, 2.4 Ast"
3,Nolan Winter,31,SO,F,6-11,220,"Lakeville, MN",Lakeville North (MN),90 (2023),"9.4 Pts, 5.8 Reb, 1.1 Ast"
4,Max Klesmit,11,SR,G,6-3,180,"Neenah, WI",Neenah HS,NaN,"9.2 Pts, 2.4 Reb, 2.7 Ast"
5,Kamari McGee,4,SR,G,6-0,180,"Racine, WI",Racine St. Catherine's HS,NaN,"6.5 Pts, 2.7 Reb, 1.8 Ast"
6,Carter Gilmore,7,SR,F,6-7,215,"Hartland, WI",Arrowhead HS,NaN,"3.9 Pts, 2.6 Reb, 1.3 Ast"
7,Xavier Amos,13,JR,F,6-8,210,"Chicago, IL",Whitney Young (IL),NaN,"3.5 Pts, 1.8 Reb, 0.4 Ast"
8,Jack Janicki,33,FR,G,6-5,190,"White Bear Lake, MN",White Bear Lake (MN),NaN,"1.9 Pts, 1.4 Reb, 0.8 Ast"
9,Markus Ilver,35,SR,F,6-8,219,"Tallinn, Estonia",Western Reserve Academy,NaN,"1.6 Pts, 0.5 Reb, 0.1 Ast"
10,Riccardo Greppi,18,FR,F,6-10,255,"Lecco, Italy",Villafrut Verona (Italy),NaN,"0.9 Pts, 1.1 Reb, 0.1 Ast"
11,Jack Robison,2,FR,F,6-5,190,"Lakeville, MN",Lakeville North (MN),NaN,"0.5 Pts, 0.3 Reb, 0.1 Ast"
12,Isaac Gard,15,JR,G,6-2,165,"Oregon, WI",Oregon (WI),NaN,"0.2 Pts, 0.2 Reb, 0.1 Ast"
13,Camren Hunter,3,JR,G,6-3,200,"Bryant, AR",Bryant HS,NaN,"0.3 Pts, 0.5 Reb, 0.1 Ast"
14,Daniel Freitag,5,FR,G,6-2,195,"Bloomington, MN",Breck (MN),NaN,"0.1 Pts, 0.3 Reb, 0.2 Ast"
15,Chris Hodges,21,JR,F,6-9,239,"Schaumburg, IL",Schaumburg HS,NaN,"0.1 Pts, 0.0 Reb, 0.0 Ast"
16,Aidan Konop,14,FR,G,6-2,195,"Sussex, WI",Sussex Hamilton (WI),NaN,"0.0 Pts, 0.0 Reb, 0.0 Ast"

In [3]:
each_game_player_stats = pd.read_csv('./data/each_game_stats_2025.csv')
each_game_player_stats

,Gtm,Date,Opp,Opp.1,Type,Rslt,Tm,Opp.2,Opp.3,OT,...,AST,AST.1,STL,STL.1,BLK,BLK.1,TOV,TOV.1,PF,PF.1
0,1,2024-11-04,Holy Cross,61,REG (Non-Conf),W,85,Holy Cross,61,NaN,...,15,8,7,4,2,2,11,12,14,20
1,2,2024-11-07,Montana State,67,REG (Non-Conf),W,79,Montana State,67,NaN,...,15,12,6,6,2,6,11,13,14,18
2,3,2024-11-10,Appalachian State,56,REG (Non-Conf),W,87,Appalachian State,56,NaN,...,17,11,14,2,1,2,6,18,18,19
3,4,2024-11-15,Arizona,88,REG (Non-Conf),W,103,Arizona,88,NaN,...,17,6,7,5,4,1,9,13,31,32
4,5,2024-11-18,Texas–Rio Grande Valley,84,REG (Non-Conf),W,87,Texas–Rio Grande Valley,84,NaN,...,10,12,5,7,1,1,9,8,16,24
5,6,2024-11-22,UCF,70,REG (Non-Conf),W,86,UCF,70,NaN,...,21,10,5,5,3,3,13,10,26,17
6,7,2024-11-24,Pittsburgh,75,REG (Non-Conf),W,81,Pittsburgh,75,NaN,...,12,11,3,1,0,0,6,8,16,19
7,8,2024-11-30,Chicago State,53,REG (Non-Conf),W,74,Chicago State,53,NaN,...,17,8,3,3,4,5,8,10,10,20
8,9,2024-12-03,Michigan,67,REG (Conf),L,64,Michigan,67,NaN,...,8,16,7,7,2,11,10,12,18,17
9,10,2024-12-07,Marquette,88,REG (Non-Conf),L,74,Marquette,88,NaN,...,16,17,3,9,1,3,14,5,18,17
10,11,2024-12-10,Illinois,86,REG (Conf),L,80,Illinois,86,NaN,...,15,15,5,3,2,2,11,13,21,22
11,12,2024-12-14,Butler,74,REG (Non-Conf),W,83,Butler,74,NaN,...,19,12,2,1,1,4,3,6,22,20
12,13,2024-12-22,Detroit Mercy,53,REG (Non-Conf),W,76,Detroit Mercy,53,NaN,...,13,5,4,4,6,1,9,8,13,17
13,14,2025-01-03,Iowa,85,REG (Conf),W,116,Iowa,85,NaN,...,26,13,4,7,0,1,12,9,16,13
14,15,2025-01-06,Rutgers,63,REG (Conf),W,75,Rutgers,63,NaN,...,15,10,5,8,5,6,16,8,15,16
15,16,2025-01-10,Minnesota,59,REG (Conf),W,80,Minnesota,59,NaN,...,14,9,9,5,2,3,7,15,13,19
16,17,2025-01-14,Ohio State,68,REG (Conf),W,70,Ohio State,68,NaN,...,6,10,2,7,2,2,12,11,19,24
17,18,2025-01-18,Southern California,69,REG (Conf),W,84,Southern California,69,NaN,...,17,13,8,6,1,0,11,15,14,18
18,19,2025-01-21,UCLA,85,REG (Conf),L,83,UCLA,85,NaN,...,14,15,3,6,1,4,13,6,23,21
19,20,2025-01-26,Nebraska,55,REG (Conf),W,83,Nebraska,55,NaN,...,18,13,5,4,3,4,8,11,11,11
20,21,2025-01-29,Maryland,76,REG (Conf),L,68,Maryland,76,NaN,...,12,13,2,4,3,4,9,7,19,18
21,22,2025-02-01,Northwestern,69,REG (Conf),W,75,Northwestern,69,NaN,...,13,16,2,5,1,4,8,5,14,17
22,23,2025-02-04,Indiana,64,REG (Conf),W,76,Indiana,64,NaN,...,13,9,8,5,3,3,6,11,15,14
23,24,2025-02-08,Iowa,63,REG (Conf),W,74,Iowa,63,NaN,...,15,12,5,5,2,3,9,9,14,15
24,25,2025-02-15,Purdue,84,REG (Conf),W,94,Purdue,84,NaN,...,18,21,2,2,4,0,3,4,14,21
25,26,2025-02-18,Illinois,74,REG (Conf),W,95,Illinois,74,NaN,...,17,13,12,6,1,5,10,14,14,18
26,27,2025-02-22,Oregon,77,REG (Conf),L,73,Oregon,77,OT,...,9,8,6,9,1,5,17,8,14,14
27,28,2025-02-25,Washington,62,REG (Conf),W,88,Washington,62,NaN,...,15,10,7,5,1,5,5,10,9,15
28,29,2025-03-02,Michigan State,71,REG (Conf),L,62,Michigan State,71,NaN,...,9,20,3,4,4,6,9,9,15,17
29,30,2025-03-05,Minnesota,67,REG (Conf),W,74,Minnesota,67,NaN,...,18,16,4,3,3,3,11,6,16,22
30,31,2025-03-08,Penn State,86,REG (Conf),L,75,Penn State,86,NaN,...,11,21,7,5,2,7,8,13,18,16
31,Gtm,Date,Opp,Opp,Type,Rslt,Tm,Opp,Opp,OT,...,AST,AST,STL,STL,BLK,BLK,TOV,TOV,PF,PF
32,32,2025-03-13,Northwestern,63,CTOURN,W,70,Northwestern,63,NaN,...,12,9,8,4,1,3,10,12,17,20
33,33,2025-03-14,UCLA,70,CTOURN,W,86,UCLA,70,NaN,...,22,13,2,4,4,3,9,5,21,19
34,34,2025-03-15,Michigan State,74,CTOURN,W,77,Michigan State,74,NaN,...,15,13,3,1,4,2,7,7,21,20
35,35,2025-03-16,Michigan,59,CTOURN,L,53,Michigan,59,NaN,...,8,14,3,3,2,2,6,8,14,16
36,Gtm,Date,Opp,Opp,Type,Rslt,Tm,Opp,Opp,OT,...,AST,AST,STL,STL,BLK,BLK,TOV,TOV,PF,PF
37,36,2025-03-20,Montana,66,ROUND-64,W,85,Montana,66,NaN,...,14,13,5,6,6,1,11,8,13,17
38,37,2025-03-22,Brigham Young,91,ROUND-32,L,89,Brigham Young,91,NaN,...,11,21,4,5,2,4,5,10,15,22
39,NaN,NaN,NaN,2622,NaN,27-10,2964,NaN,2622,NaN,...,537,468,190,176,87,121,342,357,611,685

In [5]:
per_game_player_stats = pd.read_csv('./data/per_game_player_stats2025.csv')
per_game_player_stats

,Rk,Player,Pos,G,GS,MP,FG,FGA,FG%,3P,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Awards
0,1.0,John Tonje,G,37,37,31.1,5.5,11.9,0.465,2.3,...,0.8,4.5,5.3,1.8,0.7,0.2,1.8,1.7,19.6,NaN
1,2.0,John Blackwell,G,37,37,31.2,5.5,12.2,0.451,1.6,...,1.0,4.1,5.1,2.2,0.9,0.1,2.1,2.5,15.8,NaN
2,3.0,Steven Crowl,F,37,37,25.6,3.8,7.0,0.539,0.9,...,1.4,3.9,5.3,2.4,0.5,0.5,1.4,2.1,9.9,NaN
3,4.0,Nolan Winter,F,37,37,21.1,3.4,6.1,0.564,0.9,...,1.7,4.1,5.8,1.1,0.4,0.4,0.8,1.6,9.4,NaN
4,5.0,Max Klesmit,G,33,33,27.6,2.8,8.1,0.345,1.6,...,0.2,2.1,2.4,2.7,0.8,0.1,1.1,1.7,9.2,NaN
5,6.0,Kamari McGee,G,37,4,21.9,2.3,5.0,0.457,1.1,...,0.6,2.1,2.7,1.8,0.9,0.1,0.7,2.1,6.5,NaN
6,7.0,Carter Gilmore,F,37,0,19.1,1.4,3.0,0.468,0.6,...,0.8,1.8,2.6,1.3,0.3,0.5,0.5,2.2,3.9,NaN
7,8.0,Xavier Amos,F,37,0,9.6,1.2,3.3,0.374,0.5,...,0.4,1.4,1.8,0.4,0.2,0.3,0.5,0.9,3.5,NaN
8,9.0,Jack Janicki,G,37,0,11.4,0.7,1.9,0.391,0.4,...,0.3,1.1,1.4,0.8,0.4,0.2,0.2,1.1,1.9,NaN
9,10.0,Markus Ilver,F,20,0,3.5,0.5,1.4,0.357,0.4,...,0.1,0.4,0.5,0.1,0.1,0.1,0.2,0.5,1.6,NaN
10,11.0,Riccardo Greppi,F,9,0,2.3,0.2,0.3,0.667,0.0,...,0.4,0.7,1.1,0.1,0.0,0.1,0.2,0.3,0.9,NaN
11,12.0,Jack Robison,F,13,0,1.2,0.2,0.3,0.500,0.2,...,0.2,0.2,0.3,0.1,0.0,0.0,0.0,0.1,0.5,NaN
12,13.0,Camren Hunter,G,11,0,2.1,0.1,0.7,0.125,0.1,...,0.2,0.3,0.5,0.1,0.0,0.0,0.2,0.4,0.3,NaN
13,14.0,Isaac Gard,G,13,0,1.0,0.1,0.1,1.000,0.1,...,0.0,0.2,0.2,0.1,0.0,0.0,0.0,0.1,0.2,NaN
14,15.0,Daniel Freitag,G,14,0,2.1,0.1,0.8,0.091,0.0,...,0.1,0.1,0.3,0.2,0.1,0.0,0.1,0.6,0.1,NaN
15,16.0,Chris Hodges,F,15,0,1.0,0.0,0.2,0.000,0.0,...,0.0,0.0,0.0,0.0,0.1,0.0,0.1,0.1,0.1,NaN
16,17.0,Aidan Konop,G,4,0,0.8,0.0,0.0,NaN,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
17,NaN,Team Totals,NaN,37,37,200.7,26.8,59.0,0.454,9.9,...,9.4,27.1,36.5,14.5,5.1,2.4,9.6,16.5,80.1,NaN

In [6]:
per_game_team_stats = pd.read_csv('./data/per_game_team_stats_2025.csv')
per_game_team_stats

,About,G,MP,FG,FGA,FG%,2P,2PA,2P%,3P,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,Team,37.0,40.1,26.8,59.0,.454,16.9,30.6,.552,9.9,...,.826,9.4,27.1,36.5,14.5,5.1,2.4,9.6,16.5,80.1
1,Rank,NaN,NaN,122nd,146th,142nd,280th,341st,49th,27th,...,1st,273rd,33rd,114th,109th,339th,317th,347th,206th,36th
2,Opponent,37.0,40.1,25.3,60.9,.416,17.4,37.1,.469,7.9,...,.729,9.9,24.1,34.0,12.6,4.8,3.3,10.0,18.5,70.9
3,Rank,NaN,NaN,170th,300th,61st,138th,254th,45th,234th,...,242nd,125th,181st,163rd,256th,3rd,197th,28th,315th,145th